import type {
  Agency,
  Permit,
  ProPackage,
  Region,
  RouteCondition,
  Supplier,
} from "@/lib/pro/types";

export const PRO_REGIONS: Region[] = [
  "Islamabad Capital Territory",
  "Punjab",
  "Sindh",
  "Khyber Pakhtunkhwa",
  "Balochistan",
  "Gilgit-Baltistan",
  "Azad Kashmir",
  "Lahore",
];

export const MOCK_AGENCY: Agency = {
  id: "agency-demo-1",
  name: "PakVista Partner Agency",
  country: "UAE",
  plan: "starter",
  createdAt: "2026-01-10T10:00:00.000Z",
};

export const MOCK_SUPPLIERS: Supplier[] = [
  {
    id: "sup-1",
    name: "Karakoram Expeditions",
    type: "trekking-operator",
    region: "Gilgit-Baltistan",
    district: "Hunza",
    location: "Karimabad Bazar, Hunza",
    verified: true,
    status: "verified",
    contactPublic: "Contact available for Pro plans",
    contactPrivate: "ops@karakoramexpeditions.pk | +92-300-1111111",
    languages: ["English", "Urdu"],
    pricingTier: "premium",
    description: "Expedition planning, trekking logistics, and mountain guide coordination across Hunza and upper Gilgit-Baltistan.",
    contactPerson: "Operations Desk",
    phone: "+92-300-1111111",
    email: "ops@karakoramexpeditions.pk",
    website: "https://karakoramexpeditions.pk",
    listedPublicly: true,
    applicationSource: "admin",
    submittedAt: "2026-04-12T10:00:00.000Z",
  },
  {
    id: "sup-2",
    name: "Nishat Hotels",
    type: "hotel",
    region: "Punjab",
    district: "Lahore",
    location: "Main Boulevard Gulberg, Lahore",
    verified: true,
    status: "verified",
    contactPublic: "Contact available for Pro plans",
    contactPrivate: "partners@nishathotels.pk | +92-300-2222222",
    languages: ["English", "Urdu"],
    pricingTier: "premium",
    description: "Upscale city hotel suited for FIT travelers, corporate guests, and curated Lahore stays.",
    contactPerson: "Partnerships Team",
    phone: "+92-300-2222222",
    email: "partners@nishathotels.pk",
    website: "https://nishathotels.pk",
    listedPublicly: true,
    applicationSource: "admin",
    submittedAt: "2026-04-10T10:00:00.000Z",
  },
  {
    id: "sup-3",
    name: "Lahore Tour Co.",
    type: "city-tours",
    region: "Lahore",
    district: "Lahore",
    location: "Old City, Lahore",
    verified: true,
    status: "verified",
    contactPublic: "Contact available for Pro plans",
    contactPrivate: "hello@lahoretourco.pk | +92-300-3333333",
    languages: ["English", "Urdu", "Arabic"],
    pricingTier: "mid",
    description: "Private heritage walks, food streets, and custom cultural tours across Lahore.",
    contactPerson: "Booking Office",
    phone: "+92-300-3333333",
    email: "hello@lahoretourco.pk",
    website: "https://lahoretourco.pk",
    listedPublicly: true,
    applicationSource: "admin",
    submittedAt: "2026-04-08T10:00:00.000Z",
  },
  {
    id: "sup-4",
    name: "Swat Valley Guides",
    type: "guide",
    region: "Khyber Pakhtunkhwa",
    district: "Swat",
    location: "Mingora, Swat",
    verified: true,
    status: "verified",
    contactPublic: "Contact available for Pro plans",
    contactPrivate: "bookings@swatguides.pk | +92-300-4444444",
    languages: ["English", "Urdu", "Pashto"],
    pricingTier: "mid",
    description: "Local mountain guides and custom valley experiences for Swat, Malam Jabba, and surrounding highland routes.",
    contactPerson: "Booking Office",
    phone: "+92-300-4444444",
    email: "bookings@swatguides.pk",
    website: "https://swatguides.pk",
    listedPublicly: true,
    applicationSource: "admin",
    submittedAt: "2026-04-11T10:00:00.000Z",
  },
  {
    id: "sup-5",
    name: "Makran Coast Jeeps",
    type: "transport",
    region: "Balochistan",
    district: "Gwadar",
    location: "Marine Drive, Gwadar",
    verified: false,
    status: "pending",
    contactPublic: "Contact available for Pro plans",
    contactPrivate: "ops@makrancoastjeeps.pk | +92-300-5555555",
    languages: ["English", "Urdu", "Balochi"],
    pricingTier: "budget",
    description: "Coastal transfer and off-road support for Makran itinerary planning.",
    contactPerson: "Operations Desk",
    phone: "+92-300-5555555",
    email: "ops@makrancoastjeeps.pk",
    website: "https://makrancoastjeeps.pk",
    listedPublicly: false,
    applicationSource: "partner",
    submittedAt: "2026-04-20T10:00:00.000Z",
  },
  {
    id: "sup-6",
    name: "Serena Hunza Guesthouse",
    type: "guesthouse",
    region: "Gilgit-Baltistan",
    district: "Hunza",
    location: "Eagle's Nest Road, Hunza",
    verified: true,
    status: "verified",
    contactPublic: "Family-friendly stay in upper Hunza",
    contactPrivate: "stay@serenahunza.pk | +92-300-6666666",
    languages: ["English", "Urdu"],
    pricingTier: "premium",
    description: "Boutique mountain guesthouse with valley views, local cuisine, and guided excursion support.",
    contactPerson: "Reservations Team",
    phone: "+92-300-6666666",
    email: "stay@serenahunza.pk",
    website: "https://serenahunza.pk",
    listedPublicly: true,
    applicationSource: "partner",
    submittedAt: "2026-04-18T10:00:00.000Z",
  },
];

export const MOCK_ROUTES: RouteCondition[] = [
  {
    id: "route-1",
    name: "KKH Gilgit to Sost",
    from: "Gilgit",
    to: "Sost",
    status: "open",
    lastUpdated: "2026-04-22T09:30:00.000Z",
    notes: "Normal traffic flow.",
  },
  {
    id: "route-2",
    name: "Naran-Babusar Pass",
    from: "Naran",
    to: "Babusar Top",
    status: "seasonal",
    lastUpdated: "2026-04-20T08:00:00.000Z",
    notes: "Seasonal (Jun-Oct).",
  },
  {
    id: "route-3",
    name: "Shandur Pass road",
    from: "Mastuj",
    to: "Shandur",
    status: "restricted",
    lastUpdated: "2026-04-21T11:20:00.000Z",
    notes: "Restricted movement due to weather and maintenance.",
  },
  {
    id: "route-4",
    name: "Quetta-Ziarat",
    from: "Quetta",
    to: "Ziarat",
    status: "open",
    lastUpdated: "2026-04-23T07:10:00.000Z",
    notes: "Open with minor checkpoints.",
  },
  {
    id: "route-5",
    name: "Deosai plateau entry",
    from: "Skardu",
    to: "Deosai",
    status: "closed",
    lastUpdated: "2026-04-19T15:00:00.000Z",
    notes: "Closed (winter).",
  },
  {
    id: "route-6",
    name: "Lowari Tunnel",
    from: "Dir",
    to: "Chitral",
    status: "open",
    lastUpdated: "2026-04-23T06:40:00.000Z",
    notes: "Operational for regular traffic.",
  },
];

export const MOCK_PERMITS: Permit[] = [
  {
    id: "permit-1",
    name: "K2 base camp trek",
    region: "Gilgit-Baltistan",
    issuingBody: "PTDC",
    processingDays: "6-8 weeks",
    cost: "Rs. 15,000",
    requiredFor: "High-altitude trekking and expedition access",
  },
  {
    id: "permit-2",
    name: "Khunjerab entry",
    region: "Gilgit-Baltistan",
    issuingBody: "Border authorities",
    processingDays: "Same day",
    cost: "Border fee applies",
    requiredFor: "Khunjerab border zone entry",
    notes: "CNIC/Passport + border fee",
  },
  {
    id: "permit-3",
    name: "Hingol National Park",
    region: "Balochistan",
    issuingBody: "Balochistan Tourism Dept",
    processingDays: "3-5 days",
    cost: "Varies by vehicle and group size",
    requiredFor: "Park entry for guided tours",
  },
  {
    id: "permit-4",
    name: "Deosai National Park",
    region: "Gilgit-Baltistan",
    issuingBody: "GBDMA",
    processingDays: "1 day",
    cost: "Rs. 500 per person",
    requiredFor: "National park entry",
  },
  {
    id: "permit-5",
    name: "Waziristan travel",
    region: "Khyber Pakhtunkhwa",
    issuingBody: "Home Ministry",
    processingDays: "4-6 weeks",
    cost: "Case dependent",
    requiredFor: "Restricted area travel",
    notes: "Home Ministry NOC required",
  },
];

export const MOCK_PACKAGES: ProPackage[] = [
  {
    id: "pkg-1",
    agencyId: "agency-demo-1",
    title: "Northern Highlights 7D",
    destination: "Gilgit-Baltistan",
    duration: 7,
    itinerary: [
      { day: 1, title: "Islamabad Arrival", activities: ["Client briefing", "Hotel check-in"] },
      { day: 2, title: "Fly/Drive to Gilgit", activities: ["Transfer", "Local orientation"] },
      { day: 3, title: "Hunza Valley", activities: ["Altit/Baltit", "Local market"] },
    ],
    createdAt: "2026-04-18T13:00:00.000Z",
  },
];

export const PRO_METRICS = {
  verifiedSuppliers: 214,
  openRoutesLabel: "38/44",
  packagesBuilt: 7,
  avgSupplierResponse: "4h",
};
